### PR TITLE
Use RegisterAttribute in custom view

### PR DESCRIPTION
**Pull request by albilaga**
Use RegisterAttribute to prevent error JNI handle

### CODE REVIEW

**Comment by albilaga** [comment]
I already change it to only add RegisterAttribute and also in using

**Comment by mgmclemore** [comment]
You'll need to resolve conflicts in your branch before we can merge. Thanks!

**Comment by albilaga** [comment]
Please tell me if I am doing wrong. I don't know what supposed to do. I am rebasing from master for now. Thanks

**Comment by mgmclemore** [comment]
That did it, thanks!

**Pull request merged**
